# Generated by Django 2.2.16 on 2023-03-19 17:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Капуста', max_length=200, unique=True, verbose_name='Название ингридиента')),
                ('measurement_unit', models.CharField(choices=[('g', 'г'), ('kg', 'кг'), ('ml', 'мл'), ('l', 'л'), ('piece', 'штука')], help_text='Например: кг', max_length=200, verbose_name='Еденицы измерения')),
            ],
        ),
        migrations.CreateModel(
            name='IngridientInRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Например: 1', verbose_name='количество')),
                ('ingridients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_ingridients', to='recipes.Ingridient')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Завтрак', max_length=200, unique=True, verbose_name='Название')),
                ('color', models.CharField(blank=True, help_text='Например: #E26C2D', max_length=7, null=True, unique=True, verbose_name='Цвет в HEX')),
                ('slug', models.SlugField(blank=True, help_text='Например: breakfast', max_length=200, null=True, unique=True, verbose_name='Уникальный слаг')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Яичница', max_length=200, verbose_name='Название рецепта')),
                ('image', models.URLField(help_text='Например: http://foodgram.example.org/media/recipes/images/image.jpeg', verbose_name='Ссылка на картинку готового блюда на сайте')),
                ('text', models.TextField(help_text='Описание рецепта', verbose_name='Описание рецепта')),
                ('cooking_time', models.PositiveIntegerField(help_text='Время приготовления в минутах (минимум 1 минута)', validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не может быть меньше минуты')], verbose_name='Время приготовления в минутах')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
                ('ingridients', models.ManyToManyField(related_name='recipe_ingridients', through='recipes.IngridientInRecipe', to='recipes.Ingridient', verbose_name='Ингридиенты')),
                ('tags', models.ManyToManyField(related_name='tags', to='recipes.Tag', verbose_name='Тэги')),
            ],
        ),
        migrations.CreateModel(
            name='IsInShippingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_list', to='recipes.RecipeList', verbose_name='Список продуктов из рецепта')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь корзины')),
            ],
        ),
        migrations.CreateModel(
            name='IsFavorited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_recipe', to='recipes.RecipeList', verbose_name='Рецепт')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='ingridientinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_recipe', to='recipes.RecipeList'),
        ),
    ]
