# Generated by Django 2.2.16 on 2023-03-08 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Капуста', max_length=200, unique=True, verbose_name='Название ингридиента')),
                ('measurement_unit', models.CharField(help_text='Например: кг', max_length=200, verbose_name='Еденицы измерения')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Яичница', max_length=200, verbose_name='Название рецепта')),
                ('image', models.URLField(help_text='Например: http://foodgram.example.org/media/recipes/images/image.jpeg', verbose_name='Ссылка на картинку готового блюда на сайте')),
                ('text', models.TextField(help_text='Описание рецепта', verbose_name='Описание рецепта')),
                ('cooking_time', models.PositiveIntegerField(help_text='Время приготовления в минутах (минимум 1 минута)', validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не может быть меньше минуты')], verbose_name='Время приготовления в минутах')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Завтрак', max_length=200, unique=True, verbose_name='Название')),
                ('color', models.CharField(blank=True, help_text='Например: #E26C2D', max_length=7, null=True, unique=True, verbose_name='Цвет в HEX')),
                ('slug', models.SlugField(blank=True, help_text='Например: breakfast', max_length=200, null=True, unique=True, verbose_name='Уникальный слаг')),
            ],
        ),
    ]
