# Generated by Django 2.2.16 on 2023-03-19 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230316_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngridientInRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Например: 1', verbose_name='количество')),
                ('ingridients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingridient')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipelist',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='recipelist',
            name='ingridients',
            field=models.ManyToManyField(related_name='ingridients', through='recipes.IngridientInRecipe', to='recipes.Ingridient', verbose_name='Ингридиенты'),
        ),
        migrations.AddField(
            model_name='ingridientinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeList'),
        ),
    ]
