# Generated by Django 2.2.16 on 2023-03-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230316_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=16, null=True, verbose_name='Роль'),
        ),
    ]
