# Generated by Django 2.2.16 on 2023-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230311_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль'),
        ),
    ]
