# Generated by Django 2.2.16 on 2023-03-20 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingridientinrecipe',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='ingridientinrecipe',
            name='ingridient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='in_ingridient', to='recipes.Ingridient'),
            preserve_default=False,
        ),
    ]
