# Generated by Django 2.2.16 on 2023-03-21 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230320_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridientinrecipe',
            name='amount',
            field=models.PositiveIntegerField(help_text='Например: 1', validators=[django.core.validators.MinValueValidator(1, 'Количество не может быть меньше 1')], verbose_name='количество'),
        ),
    ]
