# Generated by Django 2.2.16 on 2023-03-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230321_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelist',
            name='name',
            field=models.CharField(help_text='Например: Яичница', max_length=200, unique=True, verbose_name='Название рецепта'),
        ),
    ]
