# Generated by Django 2.2.16 on 2023-03-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230326_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='measurement_unit',
            field=models.CharField(help_text='Например: кг', max_length=200, verbose_name='Еденицы измерения'),
        ),
    ]
