# Generated by Django 2.2.16 on 2023-03-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230327_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelist',
            name='image',
            field=models.CharField(help_text='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAB', max_length=32000, verbose_name='Ссылка на картинку готового блюда на сайте'),
        ),
    ]
