# Generated by Django 2.2.16 on 2023-03-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230327_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelist',
            name='image',
            field=models.ImageField(upload_to='recipe_images/', verbose_name='Изображение блюда'),
        ),
    ]
