# Generated by Django 2.2.16 on 2023-03-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20230327_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelist',
            name='image',
            field=models.TextField(verbose_name='Изображение блюда'),
        ),
    ]
