# Generated by Django 2.2.16 on 2023-03-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20230327_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelist',
            name='image',
            field=models.ImageField(upload_to='recipe_images/', verbose_name='Изображение блюда'),
        ),
    ]
