# Generated by Django 2.2.16 on 2023-03-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20230327_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelist',
            name='image',
            field=models.ImageField(upload_to='recipes/', verbose_name='Изображение блюда'),
        ),
    ]
